// Generated from the Figma mockup text nodes (My account → Terms and Conditions / Privacy Policy).
// Content owner: Legal/Marketing. Note: the text names "Solviva Energy, OPC" — confirm the current legal entity.
export type LegalSection = { heading: string; paragraphs: string[] };

export const TERMS_META = { title: 'Standard Terms and Conditions', version: 'Mockup draft', updated: '' };
export const PRIVACY_META = { title: 'Privacy Policy', version: 'Mockup draft', updated: 'December 1, 2025' };

export const TERMS: LegalSection[] = [
  {
    "heading": "Preliminary Matters",
    "paragraphs": [
      "These Standard Terms and Conditions and the Schedules attached thereto (“STC”) are to be read together with the Contract, hereinafter collectively referred to as, the “Agreement.” SOLVIVA ENERGY, OPC is a corporation duly organized and validly existing under and by virtue of the laws of the Republic of the Philippines, with principal office address at NAC Tower, 32nd Street, Bonifacio Global City, hereinafter referred to as the “Supplier”; The Supplier is engaged in the business of providing Distributed Energy Resources (“DER”) solutions, including the sale and installation of solar photovoltaic systems (the “System”);",
      "The Buyer refers to any person or corporation identified in the relevant Contract, who desires to purchase and install a System at his/her property identified in the Contract (the “Premises”); The Supplier has determined that the Premises is capable of hosting and housing the System; and The Buyer desires to purchase the System from the Supplier and the Supplier agrees to deliver and install the System at the Premises under the terms and conditions hereinafter specified. CONTENTS: In this Agreement, words and expressions shall have the meanings respectively assigned to them in the Standard Terms and Conditions.",
      "The following documents shall be deemed to form and be read and construed as part of this Agreement: the Contract and its Annexes; the Standard Terms and Conditions; and the Schedules: Schedule 1 – Turnover Certificate and Testing and Commissioning Standards;",
      "Schedule 2 – Buyer’s Warranties; and Schedule 3 – Supplier’s Warranties. In the event of any conflict or inconsistency between the Standard Terms and Conditions of Contract and any of the Schedules, the former shall prevail."
    ]
  },
  {
    "heading": "Standard Terms And Conditions",
    "paragraphs": [
      "Definitions and Interpretation When used in this Agreement, the following terms shall have the meanings ascribed below: “Bankrupt” means, in relation to a Party, any of the following events: (i) becoming insolvent or unable to pay its debts as they fall due or being adjudicated bankrupt or insolvent;",
      "(ii) being dissolved or entering into liquidation, administration, administrative receivership, receivership, a voluntary arrangement, a scheme of arrangement with creditors, any analogous or similar procedure or any other form of procedure relating to insolvency, reorganization or dissolution, including the filing of a petition, by or against such Party, in any bankruptcy, insolvency, administration, suspension of payment, rehabilitation, reorganization, winding-up, dissolution, moratorium or liquidation proceedings, unless such petition filed against any such Party is contested in good faith by such Party in appropriate proceedings or otherwise dismissed by the relevant court within sixty (60) days from the filing of such petition; or any step being taken by any person with a view to any of those, other than a members\\' voluntary liquidation solely for the purpose of amalgamation or reconstruction on terms previously approved in writing by the other Party, such approval not to be unreasonably withheld or delayed; or (iii) ceasing to carry on business, stopping payment of its debts or any class of them, or entering into any compromise or arrangement in respect of its debts or any class of them, or any material step is taken to do any of those things;",
      "“Business Day” means a day that is not Saturday, Sunday, or a public holiday, on which commercial banks are required or authorized to be open in the Cities of Taguig and Makati, Philippines; “Commissioning Date” means the start date of the Commissioning Period; “Commissioning Period” means the period when the installed System shall be tested and commissioned; “Contract” refers to the Solar Photovoltaic System Contract or the document signed by the Buyer, detailing the System’s Specifications, Issued for Construction (“IFC”) Design, and Contract Price and Payment Scheme;",
      "“Distribution Utility” means the electric cooperative, private corporation, or government-owned utility that has an exclusive franchise to operate the distribution utility system over the area where the System will be installed; “Effective Date” means the date of execution of the Contract; “Grid” means the high voltage backbone system of interconnected transmission lines, substations and related facilities, located in each of Luzon, Visayas and Mindanao, or as may be determined by the Energy Regulatory Commission, in accordance with the Philippine Grid Code;",
      "“Hazardous Materials” means materials or substances that are or contain dangerous goods, chemicals, contaminants, toxic substances, pollutants, materials, or wastes of any kind whether solid, liquid, or gaseous or any other materials that are classified as injurious, hazardous, flammable, explosive, reactive, corrosive, infectious, radioactive, carcinogenic, toxic, or unsafe by applicable laws or applicable standards; “Practical Completion” means that the installation of the System has been completed in accordance with this Agreement, apart from minor defects which do not prevent the System from being used for its intended purpose;",
      "“Premises” means the land, building, structure or improvement where the System is to be installed and where the Services are to be performed, by the Supplier; “Specifications” means the functional specifications for the parts, components, and accessories that make up the System, as well as the specifications necessary for the proper operations of the System, as set out in the relevant Contract; and “System” means the relevant kWp solar photovoltaic power generation system, which is a power system designed to supply usable solar power by means of photovoltaics, with the Specifications set out in the relevant Contract.",
      "In this Agreement, unless the context otherwise requires: a person includes an individual, body corporate, an unincorporated association, or a government agency, and such person’s successors and assigns; a notice means all notices, approvals, demands, requests, or other communications given by one Party to the other under or in connection with this Agreement, which shall be in writing; and unless otherwise provided, if a payment or other act must be made or done on a day that is not a Business Day, then it must be made or done on the next Business Day.",
      "Term This Agreement shall become effective as of the Effective Date and will continue to be in full force and effect until the expiration of the Defects Liability Period (the “Term”), unless earlier terminated in accordance with this Agreement. The Works The scope of works under this Agreement covers the supply of the System, and installation, testing and commissioning of the System (“Works”) to the Buyer as per the Specifications detailed in the relevant Contract. The Supplier shall retain the right to refuse any changes to the Specifications that may negatively impact the System’s performance, safety and warranty.",
      "The performance of the Works shall be composed of the following phases: Preparatory Works (as described in Clause 3.4);",
      "Delivery Phase (as described in Clause 4); Installation, Testing and Commissioning Phase (as described in Clause 5); and Defects Liability Period. The Supplier will perform and complete the Works in accordance with the terms and conditions of this Agreement (including the requirements set out in the relevant Contract and good industry practices. The Supplier shall promptly advise the Buyer if the Supplier becomes aware of any circumstance which causes, or may likely cause a delay to, or otherwise affect, the performance of the Works.",
      "Preparatory Works Within fifteen (15) Business Days from the Effective Date, the Buyer shall provide the following documents (“Conditions Precedent”), which are required to be submitted to the Supplier as a condition to the commencement of the Delivery Phase: Single-line diagram of the existing electrical system at the Premises; Certification signed by a licensed civil engineer that the existing roofing structure of the Premises can accommodate additional load from the System; Schematics of equipment grounding;",
      "Documents necessary for the Supplier to process its authorizations, which are listed as Conditions Precedent in the relevant Contract [Supplier Authorizations]; Building Permit covering the Premises from the appropriate local government unit; Issued for Construction (“IFC”) Design in the relevant Contract [Issued for Construction Design] and All other permitting requirements as may be requested by the Supplier. The items specified in Clauses 3.4.1 to 3.4.7 shall collectively be referred to as “Reliance Information”.",
      "For the avoidance of doubt, the Conditions Precedent are only required for the commencement of the Delivery Phase and the submission of such Conditions Precedent shall not affect the release of the payment milestones under this Agreement.",
      "The Supplier’s (a) receipt, review, comment, and/or approval of the Reliance Information, or (b) its failure to perform (including any failure to perform correctly) any of the acts mentioned in (a), shall not be construed (i) as acceptance by the Supplier of any obligation, or (ii) as limitation on, or waiver by the Supplier, of any rights or remedies under this Agreement or applicable laws, or (iii) as a limitation or relief for the Buyer of its obligations or liabilities under this Agreement. If (i) there are deficiencies, inaccuracies, or errors in the Reliance Information;",
      "(ii) the Buyer refused or caused the deferment of a Joint Walkdown (as defined below); or (iii) the Buyer is delayed or is unable to undertake the rectification of the Premises pursuant to Supplier’s walkdown report under Clause 3.7, and there exists or occurs (A) defect or damage to the Premises or the System, or (B) death or injury to any person within or about the Premises, which could have been detected and/or prevented (x) had the Buyer submitted Reliance Information that are complete, sufficient and accurate,(y) had the Buyer participated in the conduct of the Joint Walkdown; and/or (z) had the concerns on the Premises been rectified by the Buyer, the Buyer shall: bear its own loss and pay for any costs or expenses incurred in the repair and rectification of the Premises or the System in order to ensure that the System is accommodated, installed, and in good condition; and protect, defend, indemnify, and hold Supplier harmless from and against any and all claims arising from the instances covered by this Clause 3.6 Within fifteen (15) Business Days from the Execution Date (the “Joint Walkdown Deadline”), but in no case prior to the Supplier’s receipt of the first milestone payment (except in cases where the Buyer has opted for the No Downpayment Installment scheme), and as a condition to the Supplier’s commencement of the Delivery Phase, the Parties shall conduct a joint physical inspection of the Premises (the “Joint Walkdown”), provided that the Buyer has submitted the required Reliance Information to the Supplier, in order to assess and confirm the: (i) suitability of the Premises to accommodate the System;",
      "(ii) the appropriate System Design; and (iii)the repairs and/or adjustments on the Premises to be undertaken by the Buyer prior to commencement of System installation. The conduct of the Joint Walkdown shall not be construed as (i) an acceptance by the Supplier of any obligation, or (ii) as limitation on, or waiver by the Supplier of any rights or remedies under this Agreement or applicable laws, or (iii) as a limitation on or relief for the Buyer of of its obligations or liabilities under this Agreement.",
      "Subject to Clause 3.6, the Buyer may request the Supplier to (a) dispense with the Joint Walkdown, or (b) defer the conduct of the Joint Walkdown to a date after the Joint Walkdown Deadline, subject to the prior written consent of the Supplier. Following the Joint Walkdown, the Supplier may submit to the Buyer a report on the existing conditions, defects or damage to the Premises and the proposed adjustments or rectification therefore prior to the commencement of the installation of the System.",
      "At the advice of the Supplier, the Buyer shall immediately undertake and/or bear the costs for, the adjustments or rectification of the Premises pursuant to the Supplier’s walkdown report prior to the System installation. Within thirty (30) Business Days from the conduct of the Joint Walkdown, the Supplier shall submit to the Buyer the drawings for the System design (the “System Design”). The System Design shall consist of the list of parts, components, and accessories for the System. After the Buyer has received the System Design, the Buyer shall make an independent determination that the Premises are capable of hosting the System.",
      "The Buyer shall (i) approve the System Design, or (ii) submit to the Supplier its comments to the System Design, in either case within five (5) Business Days from receipt of the System Design, as may be extended upon mutual agreement of the Parties. Should the Buyer fail to approve the System Design or submit to the Supplier its comments to the System Design within the specified period, the Parties shall consider the System Design as having been approved by the Buyer. The Supplier shall be allowed to make any necessary change to the System Design as required by the Distribution Utility.",
      "If the change to the System Design is required by the Distribution Utility, the cost sharing shall be for the account of the Buyer. If (i) the Conditions Precedent are not satisfied by the Buyer;",
      "(ii) the System Design is not completed by the Supplier; or (iii) the Buyer is unable to undertake the rectification of the Premises pursuant to Supplier’s walkdown report pursuant to Clause 3.7, within one hundred and eighty (180) days from Effective Date or such longer period as the Parties may agree upon in writing (the “Sunset Date”), either Party may terminate this Agreement immediately, and subject to a termination fee, computed as follows: [(monthly installment fee x remaining number of installments) x recovery factor)) + removal costs in the amount of Php40,000.00].",
      "On termination, this Agreement shall be of no further force or effect, save for obligations which survive termination. The recovery factor is the ratio between the number of installment payments made as of the termination of the Agreement and the total number of installment payments specified in Annex 3 [Contract Price and Payment Schedule] of the Contract. Neither Party shall be liable for, or in connection with, any claim by the other Party arising out of or in connection with the termination of this Agreement in accordance with this Clause 3.11.",
      "Should any change to the System Design be necessary due to errors in the Reliance Information, which were identified during or after the Delivery Period, the Supplier shall be entitled to revise the System Design, at the Buyer’s cost, within a reasonable period from the discovery of such errors in the Reliance Information and proceed with the installation of the System based on the revised System Design. The Supplier warrants that it shall obtain and maintain the insurance policies required under the relevant Contract.",
      "Such insurance policy shall comply with the requirements specified in Schedule 1 [Turnover Certificate and Testing and Commissioning Standards], be maintained for the duration specified therein, and be obtained and secured from a reputable insurer.",
      "Delivery Phase The Supplier shall supply and deliver, and the Buyer shall purchase and accept delivery of the parts, components, and accessories of the System as indicated in the System Design. . The Supplier shall ensure complete delivery of the System in accordance with the schedule set out in the System Design. Delivery may be made in several phases, as set out in the System Design. Delivery of the System shall be complete upon arrival of the transporting vehicle carrying the System at the place specified in the System Design or any other area as may be agreed by the Parties.",
      "The Buyer agrees to provide the Supplier with unrestricted access to all necessary sites and to cooperate fully to prevent any delay in the delivery of the System. After each delivery, the Supplier shall issue a delivery receipt to be signed by the Buyer to confirm delivery of the System (the “Delivery Receipt”). Installation, Testing and Commissioning Phase The Supplier shall be responsible for the installation of the System delivered at the Premises.",
      "The Buyer shall ensure that there are no (i) barriers, impediments, or nuisance within the Premises at all times to the installation or the performance of the System, or (ii) usage of the roof space, electrical room, and tapping points (including switchgears and transformers) of the Premises other than as may be permitted in accordance with the System Design. The Supplier shall inform the Buyer of the Commissioning Date at least three (3) Business Days prior to the Commissioning Date.",
      "If the Supplier foresees that it will not be able to commence the testing and commissioning of the System by the Commissioning Date for reasons beyond its control (including Force Majeure Events), it shall, as soon as practicable, notify the Buyer of the new Commissioning Date. The testing and commissioning of the System shall be done in the presence of the Buyer or its representative. If the Buyer or its representative does not attend the testing and commissioning of the System, notwithstanding the notice provided, the Supplier may proceed with the testing and commissioning of the System.",
      "If the Buyer or its representative has not attended the testing and commissioning, the Buyer shall accept the validity of the test readings, provided all results are within acceptable industry standards provided in Schedule 1. The Supplier shall provide the Buyer with copies of the report setting out the results of the testing and commissioning within fifteen (15) Business Days from the completion of the testing and commissioning of the System.",
      "The installation, testing, and commissioning of the System shall be considered successful and complete, and Practical Completion achieved when the key performance indicators set out in Schedule 1 are met as certified by the Supplier. The Supplier shall thereafter proceed with carrying out the remaining Works and/or repairing minor defects on the System, which do not prevent the System from being used for its intended purpose. Price and Payment The total consideration for the supply and installation of the System, as indicated in the Contract, (the “Contract Price”) is inclusive of all applicable taxes.",
      "All payments shall be made by the Buyer in accordance with the terms set out in the relevant Contract. All payments shall be paid to the Supplier’s account to be advised by the Supplier. Subject to the Supplier’s Management Team’s approval and the satisfaction of conditions as may be reasonably imposed by the Supplier, the Buyer may avail of any of the Supplier’s Payment by Installment schemes: (i) With Downpayment Installment Scheme; (ii) No Downpayment Installment Scheme. Both Parties shall cooperate and provide each other assistance in securing the necessary documents to allow any of the Parties to claim incentives under applicable laws.",
      "The Buyer further undertakes to provide the Supplier with all the necessary supporting documents (e.g., invoices, registration, licenses, permits, etc.) to allow the Supplier to claim its incentives under Republic Act No. 9513, otherwise known as the Renewable Energy Act of 2008. Obligations of the Buyer The Buyer shall be responsible for the Premises, and shall consult with an architect, engineer, and/or construction expert, as may be necessary, and make its own determination on the structural capability of the Premises to host and house the System Design.",
      "The Buyer shall be responsible for, and bear all costs associated with, applying for and obtaining all permits, licenses and approvals required for the installation, testing and commissioning of the System, as and when required, and costs associated with applying for incentives relating to the System except for those listed under the relevant Contract. The Supplier agrees to assist the Buyer in obtaining such necessary governmental permits and approvals. The Buyer undertakes to assist the Supplier in obtaining all necessary governmental permits and approvals listed in the relevant Contract.",
      "The Buyer hereby grants the Supplier and its representatives (including sub-contractors, delivery personnel, agents and other representatives) unrestricted access to the Premises at reasonable times and upon notice, for the purposes of designing, delivering, installing, inspecting, testing, commissioning, repairing, and/or removing the System, and any other purpose set forth in this Agreement (“Access Rights”).",
      "Access Rights with respect to the Premises shall include, but shall not be limited to the following: The Buyer shall provide Supplier the necessary access to the Premises and reasonable vehicular and pedestrian access within the Premises for purposes of performing Supplier’s obligations under this Agreement. In exercising such access, the Supplier shall reasonably attempt to minimize any disruption to other activities occurring at the Premises. The Buyer shall provide the Supplier with adequate storage space at the Premises for materials and tools used during delivery, installation, testing and commissioning of the System.",
      "In case installation of the System shall take two (2) or more days, the Buyer shall be responsible for providing storage and security for the System’s parts, components and/or accessories, materials and tools, at its own expense. The Supplier shall inform the Buyer of the System parts, components, and/accessories, materials and tools that need to be stored in the Premises. The Buyer shall provide the Supplier with water, drainage, electrical, and internet connections on the Premises for use by the Supplier in installing, testing, and commissioning the System. These shall be provided free of charge.",
      "The Buyer shall also be responsible for alternative sources of electricity should the Supplier require the shutting down of the supply from the Grid during critical moments for the installation, testing, and commissioning of the System. Upon the date of Practical Completion as certified by the Supplier pursuant to Clause 5.6, the Buyer shall be solely responsible for the security of the System and payment of any real property taxes attached thereto. For the avoidance of doubt, the Buyer shall be responsible for the operation and maintenance of the System as at Practical Completion, subject to Clause 9 below.",
      "For a period of two (2) years from and after the Effective Date (the “Exclusivity Period”), the Supplier will have the sole and exclusive right to install the System or any other solar or electricity generating or storage system on the Premises. In addition, in no event during the Exclusivity Period will the Buyer build or locate, or allow others to build or locate any equipment or facilities that would interfere or compete with the System. The Buyer shall report any issues in the soonest practicable time, and not tamper with the System.",
      "Defects Liability and Warranties The Supplier shall provide a warranty for the System\\'s components and its installation, starting from the date of Practical Completion, as certified by the Supplier [Defects Liability and Warranties] (the “Defects Liability Period”), in accordance with the relevant Contract. During the Defects Liability Period, the Supplier warrants that the System shall be free from defective workmanship and materials, and further warrants against non-compliance of equipment or systems with the agreed Specifications in the relevant Contract or applicable standards, fair wear and tear and degradation excepted.",
      "During the Defects Liability Period, any material, equipment or System component which proves to be defective shall be replaced by the Supplier at no additional cost to the Buyer. The Supplier shall obtain from all vendors, suppliers, manufacturers and subcontractors who supplied the System’s parts, components and accessories and/or installed, tested and commissioned the System, the warranties and/or guarantees with respect thereto, which shall be made available to the Buyer to the full extent of the terms thereof upon the discretion of the Supplier.",
      "The Supplier shall exert all reasonable efforts to assist the Buyer for the purpose of enforcing any of such warranties and guarantees, as may be needed. The Supplier’s warranties in favor of the Buyer shall in no way exceed the warranties provided by the Supplier’s vendors, suppliers, manufacturers, and subcontractors. Should the Buyer tamper with the System during the Defects Liability Period, the Supplier’s warranties under Clause 8 shall be nullified. Assignment and Subcontract The Buyer hereby allows the Supplier to assign to and engage any subcontractor to perform any part or the whole of the Works.",
      "The consent herein by the Buyer to any assignment and subcontracting by the Supplier of the Works shall not relieve the Supplier of any of its obligations under this Agreement, or from its responsibility for the Works performed by the subcontractor.",
      "Representations and Warranties Each Party represents and warrants that: if it is a juridical entity, it has been duly incorporated, validly existing, and in good standing under the laws of the Philippines and has the legal capacity and corporate power and approvals to carry on its business, to execute and deliver this Agreement and to perform its obligations and the transactions contemplated herein; it has duly and validly executed and delivered this Agreement and this Agreement constitutes a legal, valid, and binding obligation of it, enforceable against it in accordance with its terms, except as enforceability may be limited by applicable Bankruptcy, insolvency, reorganization, or other similar laws relating to or affecting the enforcement of creditors’ rights; it has obtained the authorizations and consents from third parties, if any, required to be obtained as of the date hereof for the execution and delivery of this Agreement and the performance of the obligations contemplated herein, and such authorizations and consents are in full force and effect and, as may be required by applicable laws, shall remain in full force and effect throughout the Term; it shall comply with all existing laws.",
      "Its execution, delivery, and performance of this Agreement does not contravene or violate any applicable laws or authorizations; there are no actions, suits, or proceedings pending, or to its knowledge, threatened against or affecting it before any court, arbitral tribunal, or government agency that may have a material adverse effect on its ability to observe the provisions of, or to perform its obligations under this Agreement, or on its financial condition, business, or operations; and no person or entity has been retained or employed to solicit its participation in this Agreement upon any arrangement or understanding for the payment of any commission, fee or other compensation of any kind, and that neither it nor any of its officers, directors, employees, agents or affiliates have made, received, provided or offered any gift, entertainment, payment, loan or other consideration for the purpose of influencing the procurement of any particular item required for the Works or the selection of any particular supplier or subcontractor (and shall not do so).",
      "The Buyer further represents and warrants the truth and veracity of all the facts stated in Schedule 2 [Buyer’s Warranties] and undertakes to perform or cause the performance of the deeds, actions, or things specified in Schedule 2. The Supplier further represents and warrants the truth and veracity of all the facts stated in Schedule 3 [Supplier’s Warranties] and undertakes to perform or cause the performance of the deeds, actions, or things specified in Schedule 3. Hazardous Materials The Supplier shall not be responsible for any Hazardous Materials encountered at the Premises, except to the extent introduced solely by the Supplier.",
      "Upon encountering any Hazardous Materials, the Supplier shall stop work in the affected area. Both the Supplier and Buyer shall take all measures required by applicable law to address the Hazardous Materials discovered at the Premises. If the presence of Hazardous Materials in the Premises affects the capability of the Premises to host and house the System, (i) the Buyer shall undertake to remove such Hazardous Materials in compliance with applicable laws, and in any case within five (5) Business Days, or (ii) the Supplier and the Buyer may agree upon a different location for the System.",
      "In case of Clause 11.2(i), if the Buyer fails to remove such Hazardous Materials, the Supplier may opt not to proceed with the installation of the System and consider such failure as Buyer’s breach of this Agreement.",
      "The Supplier shall resume work at the affected area(s) of the Premises only after both the Supplier and Buyer determine that there has been compliance with all applicable laws, and a qualified independent expert agreed upon by the Parties (at the sole cost of the Buyer) provides a written certification stating the following, if applicable: (i) remediation has been accomplished as required by applicable laws, and (ii) all necessary approvals have been obtained from the appropriate governmental authority having jurisdiction over the System or the Premises.",
      "The Buyer shall reimburse the Supplier for any and all additional costs (including demobilization and remobilization expenses) incurred by the Supplier in the installation of the System resulting from the presence of Hazardous Materials and/or the remediation of the Premises. Notwithstanding the preceding provisions, the Buyer shall not be responsible for any Hazardous Materials introduced to the Premises by the Supplier, nor is the Buyer required to remediate an affected area if such remediation is deemed to be economically unjustifiable or otherwise impractical.",
      "Force Majeure Neither Party shall be liable for any delay in performing or for failure to perform its non-financial obligations or Works hereunder to the extent that and for so long as the delay or failure results from any cause or circumstance whatsoever beyond its reasonable control (\"Force Majeure Event\"), provided the same (i) is not caused by the act, omission, negligence, or willful misconduct of the affected Party, (ii) is beyond the reasonable control of the affected Party, and (iii) the effects of which could not reasonably have been prevented or overcome by the exercise of reasonable care or diligence.",
      "For purposes of this Agreement, the term “Force Majeure Event” may include, but is not limited to, the following events or circumstances: acts of war or of a public enemy (whether war be declared or not), terrorism, invasion, armed conflict or act of foreign enemy, blockage, embargo, revolution, and public disorders, including insurrection, rebellion, civil commotion, sabotage, riots, and violent demonstrations; accidents, explosions, fires, earthquakes, typhoons, tidal waves, storm surges, flooding, or other natural calamities or severe or unfavorable weather conditions; discovery of hazardous materials at the Premises; unavailability of facilities or materials, or transportation failures which are unforeseeable and against which a reasonably prudent person would not have taken precautions; with respect to the Supplier only, strikes or lockouts or other industrial action by its employees, or of any contractor, or any subcontractor of any contractor of the Supplier; with respect to the Supplier only, any outages in the transmission system or distribution utility system; or with respect to the Supplier only, provided there is no fault on its part, (a) any action or failure to act by any government agency or any agent thereof, including without limitation, expropriation, compulsory acquisition, the denial, conditioning, variation, termination or voiding of, or failure, or delay in the granting or renewing of any authorization which is required for Supplier’s due application therefor;",
      "(b) any delay in the importation of equipment or supplies into the Philippines resulting from any action or failure to act by any government agency or agent thereof; (c) any change in government agency requirements in force from time to time after the Execution Date; or any change in applicable law affecting the performance of Supplier’s obligations.",
      "If any Force Majeure Event occurs, and subject to the affected Party promptly notifying the non-affected Party in writing of the same within five (5) days from the time the affected Party becomes aware of the occurrence of the Force Majeure Event, the date(s) for performance of the obligation or Works affected shall be postponed for so long as is made necessary by the Force Majeure Event.",
      "The written notice (“FM Notice”) to be provided by the affected Party to the non-affected Party shall contain, among others: the nature and extent of the Force Majeure Event; and the effect the affected Party reasonably expects the Force Majeure Event will have on its obligations under this Agreement. Each Party shall use its reasonable endeavors to overcome or minimize the effects of any Force Majeure Event.",
      "Neither Party shall be in default under this Agreement, nor shall be liable to the other for any delay in or failure of performance of the terms of this Agreement if and to the extent such delay or failure is attributable to a Force Majeure Event. Each Party shall be liable for and shall bear all of its own losses suffered and incurred as a result of an occurrence of a Force Majeure Event. The affected Party shall, promptly after a Force Majeure Event ceases to prevent or delay its performance of obligations and/or Works pursuant to this Clause 12: notify the other Party in writing; and resume performance of those obligations and/or the Works.",
      "Variations Notwithstanding anything to the contrary in this Agreement, either Party may require a change, addition, omission, substitution of the Works (“Variation”) at any time during the Term; provided, that the Parties agree to the terms and conditions of the Variation prior to the execution thereof. Both Parties shall execute and be bound by each Variation executed in writing by the Parties, and this Agreement shall be considered so amended to the extent thereof. In the event that the Parties fail to agree on the Variation, the terms of this Agreement as originally agreed to shall apply.",
      "Confidentiality and Publicity The Parties agree, during the Term and five (5) years from the termination or expiry hereof, to hold in strictest confidence, and not to use, except (i) for the benefit and for the purposes of this Agreement and (ii) to enforce its rights or defend any claim or action under or in connection with this Agreement; or to disclose to any person, firm, or corporation without the prior written authorization of the disclosing Party or being compelled by competent government authority (after giving prior written notice to the concerned Party of any writ or order from such government authority), any Confidential Information disclosed by one to the other.",
      "For purposes of this Agreement, “Confidential Information” means any of the disclosing Party’s information, drawings, technical data, trade secrets, or know-how, including, but not limited to, research, product plans, products, services, customer lists, markets, software, developments, inventions, processes, formulas, technology, designs, drawings, engineering, hardware configuration information, marketing, finances, or other business information disclosed by one Party to the other, either directly or indirectly, in each and every case regardless of whether such information is marked “confidential” or “proprietary” and in whatever form supplied or received.",
      "“Confidential Information” does not include information available in the public domain prior to disclosure or which, through no fault of the Party receiving the Confidential Information, became publicly available after such disclosure. Either Party may use the Confidential Information to the extent necessary for negotiations, discussions, and consultations with each other’s authorized personnel or representatives or for any other purpose the disclosing Party may hereafter authorize in writing.",
      "Neither Party is allowed to issue any information, publication, or media release concerning this Agreement or the System without the prior consent of the other party.",
      "Nothing in this Agreement shall be construed as preventing the Supplier from disclosing Confidential Information including personal information provided by the Buyer to (i) Supplier’s advisors and potential lenders in so far as necessary to obtain loan facilities or to comply with loan covenants, and (ii) Supplier’s potential investors including these potential investor’s counsel, advisors, banks, or other financial institutions in so far as necessary to obtain capital or other forms of funding.",
      "To this end, the Buyer consents to such disclosure and affirms that it has the right to authorize the Supplier to share and disclose such information in accordance with this Clause 14.4 Intellectual Property All materials and other information furnished by the Supplier to the Buyer, including without limitation, the confidential and proprietary information referred to herein, shall be retained as the sole and exclusive property of the Supplier or by persons from whom the Supplier has obtained the licenses or permits to use the intellectual property rights for the Works.",
      "Mutual Covenant to Provide and Maintain a Safe Business Environment 17.1 The Supplier and Buyer are committed to providing and maintaining a safe business environment that respects the dignity of all persons. The Parties do not tolerate any form of abuse, be it physical, verbal or psychological and any form of sexual or gender-based sexual harassment, or similar actions (collectively, referred to as “abusive behavior”) towards any of its representatives, agents, employees, and subcontractors. 17.2 For the avoidance of doubt, abusive behavior includes, but is not limited to: 17.2.1.",
      "Physical abuse which refers to any act, threat, or attempt to cause bodily harm or injury or any act which places an individual in fear of imminent physical harm; 17.2.2. Verbal abuse which includes but is not limited to verbal threats, derogatory or harmful statements, or any statements causing or likely to cause public ridicule or humiliation; 17.2.3. Psychological abuse includes acts, omissions or utterances causing or likely to cause mental or emotional suffering/ anguish on the part of the receiver; 17.2.4.",
      "Gender-based sexual Harassment include among others: catcalling, wolf-whistling, unwanted invitations, misogynistic, transphobic, homophobic and sexual slurs, persistent uninvited comments or gestures on a person’s appearance, relentless requests for personal details, statement of sexual comments and suggestions, lewd sexual behaviors, any advances, whether physical or verbal would place a person in fear of his/her personal space and physical safety, including cursing, leering, taunting, persistent sexual jokes, use of sexual names and stalking; and 17.2.5.",
      "Any other acts considered as a form of physical, verbal or psychological abuse and sexual or gender-based harassment under existing laws. 17.3 Notwithstanding the other clauses in this Agreement, on the basis of any reported abusive behavior or alleged acts of abusive behavior committed by any representative, agent, employee or subcontractor of a Party, the offended Party shall notify in writing the offending Party of the infraction and demand the rectification or correction of such behavior.",
      "If the offending Party does not correct its infraction within a reasonable period, the offended Party may avail of the dispute resolution process pursuant to Clause 18. 17.4 Both Parties are expected to fully cooperate on any investigations that might stem from the occurrence of such abusive behavior.",
      "Termination Either Party shall have the right (in addition to any other rights which it has under applicable law) to terminate this Agreement immediately upon the occurrence of any of the following: if the other Party commits a breach of any of the provisions or any of its covenants under this Agreement and fails to remedy such breach (if capable of remedy) within thirty (30) days after receipt of a request in writing from the other Party; if the other Party becomes bankrupt;",
      "If payments are not made within three (3) days after the Payment Date; [If the Buyer makes a general assignment of its assets or business for the benefit of its creditors; if there is a change of ownership, control, merger, or consolidation of the business of the Buyer, without prior written consent of the Supplier; if the Buyer ceases its business operations or permits its license or authority to conduct its business to expire or be revoked without said license being immediately renewed; or if a Party or any of its employee, agent, representative or subcontractor, has engaged in corrupt, fraudulent, collusive, coercive or obstructive practices, in competing for, executing or performing this Agreement.",
      "Termination of this Agreement shall not affect any antecedent and accrued rights, obligations, or liabilities of either Party, nor shall it affect any provision of this Agreement which is expressly or by implication intended to come into or continue in force on or after such termination.",
      "The Supplier shall have the right (in addition to any other rights which it has under applicable law) to terminate this Agreement if: the Joint Walkdown does not occur within thirty (30) days from the original Joint Walkdown Deadline without the Supplier’s consent; any government regulatory body fail to approve the interconnection of the System to the Premises or require materially different equipment in addition to the Goods set out in the System Design; or the Buyer breaches any of its obligations, representations and warranties under this Agreement.",
      "Notice of Termination: The Supplier may, without any liability, terminate this Agreement before the expiration of the term by: Giving a thirty (30)-days written notice to the Buyer, if the termination is without cause;",
      "Giving a fifteen (15)-day written notice to the Buyer, if the termination is based on any breach or violation by the Buyer of its obligations and/or any other provision of this Agreement, including breach of its representations and warranties, and only if such breach is, in the Supplier’s reasonable opinion, remediable, as otherwise, the Supplier may terminate with immediate effect; or Giving notice of the termination to the Buyer, effective immediately, for causes under Clause 17.1 above. 18.4 For the avoidance of doubt, upon termination of this Agreement for any reason, the Supplier shall be entitled to receive such compensation and reimbursement, if any, accrued under the terms of this Agreement, but unpaid, as of the date the Supplier ceases work under this Agreement. 18.5 The termination of this Agreement shall be in addition to, and not in lieu of other rights and remedies of the each Party under this Agreement and existing provisions of law.",
      "Dispute Resolution If any dispute, controversy, claim or difference of any kind whatsoever shall arise between the Parties in connection with this Agreement, including the breach, termination or validity of this Agreement (each, a “Dispute”), the Parties shall attempt, for a period of thirty (30) days reckoned from receipt by a Party of a written notice from the other Party stating the existence of a Dispute, to settle such Dispute in the first instance by mutual discussions between the duly authorized representatives of the Parties.",
      "For Contracts with a Contract Price equivalent to Philippine Peso: Two Million (Php2,000,000.00) or less: If the Dispute is not settled by mutual discussions in accordance with Clause 18.1, all actions, or claims arising under or relating to this Agreement shall be brought exclusively before the proper courts in the City of Makati to the exclusion of all other venues.",
      "For Contracts with a Contract Price of more than Philippine Peso: Two Million (Php2,000,000.00): If the Dispute is not settled by mutual discussions in accordance with Clause 18.1, all actions, or claims arising under or relating to this Agreement shall be referred to and finally resolved by arbitration in accordance with the Philippine Dispute Resolution Center, Inc. (“PDRCI”) Arbitration Rules in force when the notice of arbitration is submitted. The number of arbitrators shall be one, whose selection shall be mutually agreed by the Parties, and failing to do so, shall be determined in accordance with the PDRCI Arbitration Rules.",
      "The place of arbitration shall be in Taguig City. The language to be used in the arbitral proceedings shall be English. The arbitration clause shall be interpreted in accordance with the laws of the Republic of the Philippines. During the pendency of any proceedings under Clause 18.1 or 18.2, (i) the Parties shall continue to perform their respective obligations under this Agreement and comply with the terms and conditions of this Agreement that are not in dispute, and (ii) neither Party shall exercise any other remedy hereunder arising by virtue of the matters in dispute, unless this Agreement is terminated in accordance with Clause 18.1.",
      "Nothing in this Clause 18 shall prevent any Party from seeking interim injunctive or other provisional relief as may be available under applicable laws.",
      "Indemnification The Supplier has entered into this Agreement in reliance on the warranties and information provided by the Buyer herein stated, including the Buyer’s express representation that it is legally competent to own and operate the Goods and System, respectively, to be provided by the Supplier in accordance with the terms of this Agreement.",
      "The Buyer shall hold free and harmless and shall defend, compensate, and fully restore the Supplier from any claims by any person or entity for any violation or breach of any law, contract, or obligation made by the Supplier as a result of the latter’s reliance on the Buyer’s warranties and representations.",
      "A party (the “First Party”) shall hold harmless the other party (the “Second Party”) from and against any and all damages incurred by reason of (i) any failure by the First Party to perform any Works, covenant or obligation, or any breach by the First Party of any representation, warranty, or covenant under this Agreement; or (ii) personal injury to, or the death of, any person or any damage to or loss of property, which is due to the fault, negligence, and/or willful acts of the First Party.",
      "Neither Party shall be liable to the other for any special, consequential, or punitive damages or indirect costs or expenses or loss of profit, loss of production, loss of contracts, or for any indirect or consequential loss whatsoever that may be suffered by the other, whether such liability arises in contract, breach, tort (including negligence and strict liability) or otherwise. Clause 19.3 does not apply to a Party’s liability in respect of the wilful misconduct, gross negligence, fraud, illegality or unlawful acts or omissions of that Party.",
      "Notwithstanding any other provision of this Agreement, but subject to Clause 19.6, each Party’s aggregate liability to the other Party arising out of or in connection with this Agreement and the Works (whether under contract, in tort (including negligence), under statute or otherwise at law or in equity (including in respect of an indemnity, warranty or representation in this Agreement) is limited to one hundred percent (100%) of the Contract Price.",
      "Clause 19.5 does not apply: in respect of a Party’s liability in respect of the wilful misconduct, gross negligence, fraud, illegality or unlawful acts or omissions of that party; in respect of the a Party’s liability under or in connection with the indemnity in Clause 19.2;",
      "Miscellaneous This Agreement shall be governed by the laws of the Republic of the Philippines. Where this Agreement is signed on behalf of a Party, the signatory represents that he or she is authorized to do so. Nothing in this Agreement shall be construed as creating a joint venture, partnership, franchise, agency, employer/employee, or similar relationship between the Parties. This Agreement is the complete and exclusive statement of the agreement between the Parties and supersedes all proposals or prior agreements, oral or written, and all other communications between the Parties relating to the subject matter of this Agreement.",
      "The index and headings of the Clauses herein are used for convenience and ease of reference only, and in no way shall limit or describe the scope or intent of this Agreement or any of its provisions. Both Parties acknowledge and agree that they have fully read and understood the contents of this Agreement and that the same shall be considered to be jointly drafted. The Parties undertake to act in good faith and with respect to each other’s rights under this Agreement and to adopt all reasonable measures to ensure that the objective and purpose of this Agreement are realized.",
      "Whenever possible, each provision of this Agreement will be interpreted in such manner as to be effective and valid under applicable law, but if any provision of this Agreement is held to be invalid, illegal, or unenforceable in any respect under any applicable law, such invalidity, illegality, or unenforceability will not affect any other provision, and this Agreement will be reformed, construed, and enforced as if such invalid, illegal, or unenforceable provision had never been contained herein.",
      "Any Variation to or amendment to any term or condition of this Agreement shall be in writing and shall be signed by the duly authorized representative of the Parties. No waiver of a breach, failure of any condition, or any right or remedy contained in or granted by the provisions of this Agreement shall be effective unless it is in writing and signed by the Party waiving the breach, failure, right, or remedy.",
      "This Agreement, constitutes the final, complete, and exclusive statement of the agreement of the Parties with respect to the subject matter hereof, and supersedes any and all other prior and contemporaneous agreements and understandings, both written and oral, between the Parties. This Agreement may be executed in any number of counterparts; all counterparts together constitute one instrument.",
      "Schedule 1 – Turnover Certificate and Testing and Commissioning Standards To be shared post-installation Schedule 2 – Buyer’s Warranties The Buyer further represents, warrants, and undertakes the following: 1.1 all the information the Buyer shall give to the Supplier, including but not limited to the Reliance Information, are and will be complete, accurate, adequate, reliable, and correct in all material respects and are not and will not be misleading and do not and will not omit material facts as of the dates of such information and when provided to the Supplier, and that the Supplier may rely on such information as provided by the Buyer; 1.2 the Buyer’s documents do not infringe on any third party’s intellectual property rights; 1.3 it has the legal and beneficial right to occupy, use, and possess the Premises and the land where the Premises are situated, and has the full power, authority, and legal right, and has all the authorizations and consents from third parties, to allow the Supplier to use and access the Premises in accordance with this Agreement and to convey the rights and privileges granted to the Supplier under this Agreement and for the Supplier to exercise such rights and privileges in accordance with this Agreement.",
      "The Buyer warrants the Supplier’s full, peaceful, quiet, uninterrupted and optimal enjoyment of all the rights and privileges under this Agreement; and 1.4 it shall maintain and preserve its corporate existence, rights, privileges, authorizations and its right to carry on its business operations in good standing in accordance with applicable law and sound financial and business practices and its business plan, save to the extent that any failure to do so could not reasonably be expected to have a material adverse effect on the business, financial condition, or results of operation of the Buyer.' 1"
    ]
  }
];

export const PRIVACY: LegalSection[] = [
  {
    "heading": "",
    "paragraphs": [
      "Last updated: December 1, 2025 SolViva Energy OPC\\xa0(“Company”, “we”, “us”, or “our”)\\xa0respects and values your privacy. We are committed in ensuring that our policies and practices with respect to the collection and processing of personal data are in accordance with Republic Act No. 10173 also known as the Data Privacy Act of 2012 (“DPA”), its Implementing Rules and Regulation (“IRR”),issuances of the National Privacy Commission (“NPC”) and other applicable laws on data privacy, privacy protection and security (collectively, the “Privacy Laws”), as well as our internal Company data privacy and protection policies.",
      "This Privacy Policy (“Policy”) describes how the Company collects, processes, uses, stores, discloses, transfers, and disposes of the Personal Data that you share with us. This Policy also explains your rights in relation to your Personal Data and how to contact our Data Privacy Officer. \\xa0This Policy likewise details the measures taken by the Company to protect and secure the Personal Data collected and processed and steps undertaken to ensure that your rights as the \\xa0data subject are upheld and observed.",
      "From time to time, it may be necessary for you to provide Personal Data, defined and described below,\\xa0in connection with the following activities, namely: accessing our Company website and portals, which includes browsing through any of our websites or mobile applications; requests for quotation or product information; visiting our physical offices; participating in gatherings and events organized or sponsored by our Company; participating in the Company’s promotional activities, including joint promotions with third-party partners; any and all direct or indirect dealings with our Company, our officers and employees, as an investor, a shareholder, job applicant, an employee, a stakeholder, a customer, or in any other relevant capacity, including but not limited to invitations for polls and surveys circulated via electronic emails."
    ]
  },
  {
    "heading": "The Personal Data We Collect",
    "paragraphs": [
      "We may collect and process data from you in the ordinary course of our business or to the extent necessary to respond to your requests, queries, and concerns which may include, basic information such as your name, residence, and contact details; sensitive personal information such as your age, financial information, biometric data, birthdate; educational background, ID with picture employment history, gender, government issued identifications, licenses, and certifications, health data (medical history, data on disability, medical diagnosis, opinions, fitness apps, Vascular scan), marital status, photograph, place of birth, proceeding for any offense committed or alleged to have been committed by an individual, signatures, financial information such as bank statements, financial statements, payslips, social security number, tax identification number, tax returns, titles and other evidence of ownership, among others (“Personal Data”).",
      "When you visit our websites or use any of our mobile applications, other such as browser type, operating system, IP address, domain name, number of times the website or the mobile application was accessed, including the frequency of such access, may be collected via cookies and other tracking technologies, such as transparent GIF files. Aggregate information, or non-personally identifiable and anonymous data, such as how many times you log onto our websites or mobile applications may also be collected.",
      "The transmission of such personal data is implicit in the use of web communication protocols or is useful for the improved management and optimization of the data and electronic mail sending system. Third-Party Social Media Login Data We may also collect your Personal Data when you choose to access our services through third-party social media login providers (such as Facebook, Google, or LinkedIn). By doing so, you authorize the third-party platform to share certain personal data with us, such as your name, email address, profile picture, and any other data you have chosen to make available through your privacy settings on that platform.",
      "This allows us to enhance our services and provide a more personalized experience. We only collect and process this Personal Data within the limits of your consent and in accordance with the Privacy Laws. You will be notified of the data that will be shared by the third-party provider and have the option to modify the permissions through your social media account settings. All collected data will be treated in accordance with our policies and retained only as necessary to fulfill the purposes stated."
    ]
  },
  {
    "heading": "How We Use Cookies And Tracking Technologies",
    "paragraphs": [
      "A cookie is a small file which asks permission to be placed on your computer’s hard drive. Cookies allow websites to recognize your computer when you return, enabling it to display personalized settings and other user preferences. It also allows websites to respond to you as an individual. The websites and apps can tailor operations to your needs, likes and dislikes by gathering and remembering information about your preferences. We use traffic log cookies to identify which pages are being visited. This helps us analyze data about webpage traffic and improve our website in order to tailor it to your needs.",
      "We only use this information for statistical analysis purposes after which, the data is removed from the system. In general, cookies help us provide you with a better website experience, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us. You will be given the opportunity to accept or reject the use of cookies on our websites in a pop-up box when you first access our website.",
      "Once you agree, the file is added and the cookie helps analyze web traffic or lets you know when you visit a particular site. Most web browsers, however, automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. You may choose not to accept cookies; however, this may restrict the services that you can access at our websites. Declining cookies may also prevent you from taking full advantage of our websites."
    ]
  },
  {
    "heading": "How We Use The Personal Data We Collect",
    "paragraphs": [
      "When necessary, we request for your Personal Data for us to understand your needs and provide you with better service. We will process such Personal Data for specific purposes and only where there is a specific legal basis for doing so as laid down by the Privacy Laws.",
      "Specifically, we will process your Personal Data for the following purposes (the “Purpose”): As an investor or stockholder of record: Establishing your identity as an investor or a stockholder of record in order to provide you services and accord you the benefits of an investor or a stockholder, which includes managing, administering, approving or facilitating any transaction or action in relation to your shares of stock, the payment of your dividends, and the registration of your shares in the stock and transfer books; and Collecting and analyzing collective investor or shareholder data or information, and conducting statistical analysis to improve the services to be provided to you including the expeditious response to your concerns and queries, and to ensure that the services to be provided to you as an investor or a stockholder of record are based on accurate and appropriate information As a job applicant: Establishing your identity and qualification as a job applicant.",
      "As an employee: Providing you with compensation and benefits that come with your employment in the company; Offering you with opportunities for learning and career advancement; Maintaining personnel and workplace health and safety standards; Participating in our Company initiatives and events; Maintaining company correspondence; Promoting employee engagement and well-being; Protecting employee vital interests; Complying with law and regulation or legal obligation;",
      "Marketing and promoting core human resources services; and Processing people analytics to improve organizational capability, enhance employee experience or solve business problems for and on behalf of the Company As a customer: Answering queries and addressing concerns; Fulfilling contractual agreements and obligations; Improving the quality of our services; Developing new offerings to meet your needs; Promoting customer attraction or retention programs, value added services, data analytics and other statistical and analytical studies and for such other legitimate commercial and marketing purposes;",
      "Assessing your continued qualification for availment of our services; Maintaining or updating the Company’s customer records; Updating you on the Company’s activities or other services which may interest you through direct multi-channel (Viber/SMS) marketing; and Building our statistical and analytical studies and database for internal reporting. As a stakeholder in any relevant capacity: Complying with the due diligence requirements in fund-raising activities and transactions with lenders, creditors or financial institutions;",
      "Complying with the reportorial obligations of the Philippine Stock Exchange (PSE) and the Philippine Dealing and Exchange Corporation (PDEx), and other self-regulating organizations that oversee the company; Complying with the requirements of regulatory agencies and instrumentalities of the government including, but not limited, to the Securities and Exchange Commission (SEC) and the Bureau of Internal Revenue (BIR); Complying with and responding to legal processes or lawful orders of any judicial or quasi-judicial bodies; and Maintaining business correspondence."
    ]
  },
  {
    "heading": "How We Process Your Personal Data",
    "paragraphs": [
      "We collect and process the Personal Data you provide\\xa0via electronic mail, website footprint, Meta forms, through our third-party service providers or as provided in physical documents disclosed and transmitted. Personal Data collected may be recorded and stored in both digital or electronic format, and in physical copies. Access to information is limited to authorized officers and personnel for the purpose of your engagement and through your transactions with us. We may organize or consolidate the above-enumerated Personal Data to allow us to use the same for the foregoing purposes.",
      "We may also retrieve any of your stored data for the same purposes, as well as to update, modify or correct your data upon your request. In all instances, the Company ensures that collection and processing are not undertaken through use of deceptive design patterns."
    ]
  },
  {
    "heading": "Security And Retention Of Personal Data",
    "paragraphs": [
      "We are committed to ensuring that your Personal Data is kept secure. We have implemented suitable and adequate organizational, physical and technical security measures, policies and procedures intended to reduce the risks of accidental destruction or loss, the unauthorized disclosure or access to such information which are appropriate and adequate to the nature of the Personal Data we collect, and such other personal breaches and security incidents as defined under the Privacy Laws.",
      "We implement the appropriate disposal (physical or electronic) of policies for documents, records, and assets to ensure that Personal Data are disposed or discarded in a secure manner that would prevent further processing, unauthorized access, or disclosure to any other party or the public, or prejudice the interests of the data subjects. We may retain your Personal Data only for as long as necessary for legitimate business purposes in line with the principle of proportionality, to comply with laws, regulations, or lawful court order, or to establish or defend a legal action."
    ]
  },
  {
    "heading": "Disclosure Of Personal Data",
    "paragraphs": [
      "We may disclose your Personal Data with any of our Company affiliates or subsidiaries for the purposes of processing and documenting, profiling, statistical analysis, customer insights, credit scoring, marketing, and other analogous processes necessary to enable data sharing including cross selling of data across the affiliates and subsidiaries of the Company to the extent allowed by the Data Privacy Laws, as specified under the relevant Data Sharing Agreements.",
      "The Company may also disclose or share your Personal Data to the following third parties as may be necessary to achieve the foregoing purposes, pursuant to data sharing agreements to be entered or similar documents to be executed embodying the data sharing arrangement: any agent, contractor, or sub-contractor performing services related to stockholders services; any consultant, adviser, auditor, or service provider we engaged to carry out functions or activities related to our legitimate business activities; any person to whom we propose to assign or transfer any of our rights and/or duties; any of our affiliates and subsidiaries, partner companies, and service providers with whom we have contracted through data sharing agreements for promotion of customer attraction or retention programs, value added services, data analytics and other statistical and analytical studies and for such other legitimate commercial and marketing purposes; any court of law or administrative agency of the government pursuant to a lawful order issued in relation to a pending case or proceeding before such court or agency; our lenders or creditors, underwriters, as well as the consultant, adviser or, auditor of the foregoing; your lawyer, attorney-in-fact, or duly authorized agent or representative, upon presentation of a duly executed special power of attorney; and any regulatory, quasi-judicial or judicial authority, or as otherwise considered necessary or appropriate for our legitimate business purposes.",
      "Any access to Personal Data will be limited to the person who requires your Personal Data to perform the functions for collection has been undertaken, and as required or allowed by law. We do not sell, trade, or otherwise transfer your Personal Data to third parties without a data sharing agreement compliant with the Privacy Laws. We will comply with the data sharing provisions of the Privacy Laws or obtain your prior consent, as may be necessary, should we share your Personal Data to third parties. Any data sharing for commercial purposes will be covered by a data sharing agreement.",
      "For the comprehensive list of the Company's subsidiaries and affiliates, please see our Conglomerate Map."
    ]
  },
  {
    "heading": "Data Sharing And International Transfers",
    "paragraphs": [
      "Our service providers, which may or may not be located outside the Philippines, may also have access to the Personal Data, for reasons relating to the Purpose. Where we consider it necessary and appropriate for one or more of the Purposes in this Policy, we may transfer your personal data to our services providers outside the Philippines. In such instances, the Company shall take necessary steps to ensure that such transfer complies with the requirements for cross-border data transfer\\xa0as mandated under the Privacy Laws. \\xa0 SECURITY AND RETENTION OF PERSONAL DATA We are committed to ensuring that your Personal Data is kept secure.",
      "We have implemented suitable and adequate organizational, physical and technical security measures, policies and procedures intended to reduce the risks of accidental destruction or loss, the unauthorized disclosure or access to such information which are appropriate and adequate to the nature of the Personal Data we collect, and such other data breaches and security incidents as defined under the Privacy Laws."
    ]
  },
  {
    "heading": "Links To Other Websites",
    "paragraphs": [
      "The privacy statements set forth in this Policy are for purposes of your engagement and interaction with us only. This website may contain links to other sites. The Company is not responsible for the privacy practices or the content of such sites. If you link to or otherwise visit any other site, please review its corresponding privacy policy."
    ]
  },
  {
    "heading": "Cookies And Passive Tracking",
    "paragraphs": [
      "A “cookie” is an element of data that can be sent to your browser. Your browser may then store it on your system based on the preferences you have set on your browser. Cookies gather information about your operating system, including but not limited to the type and Internet Protocol (IP) address. The Company uses such information to analyze the traffic on our website and to better serve you when you return to our website. It is not our intention to use such information to personally identify a user.",
      "You have the option to configure your Internet browser to notify you when you receive a cookie, giving you the chance to decide whether to accept it or not. Further, you have the option to block all cookies. Please note, however, that if you refuse or otherwise block cookies, you may not be able to use all of the functionality available on this website."
    ]
  },
  {
    "heading": "Notification Of Changes",
    "paragraphs": [
      "We reserve the right to amend or update this privacy statement as necessary. Any substantial changes regarding the scope, purpose, nature, or extent of data processing will be made in adherence to the universally accepted Privacy Laws. We recommend that you check this privacy notice periodically to stay informed of any updates to our policies."
    ]
  },
  {
    "heading": "Your Rights As Data Subject",
    "paragraphs": [
      "Based on the provisions provided under the Privacy Laws, we uphold the following rights data subjects, namely: Right to be informed.\\xa0As a data subject, you have the right to be informed that your Personal Data will be, are being, or were, collected and processed. Right to access.\\xa0In relation to your right to be informed, you also have the right to gain reasonable access to your Personal Data, such as: (a) contents of your Personal Data that were processed; (b) manner by which such Personal Data were processed; (c) date when your Personal Data was last processed and modified, among others.",
      "Right to object.\\xa0You have a right to object to the processing of your Personal Data, including automated processing or profiling. Likewise, you have the right to be notified and given an opportunity to withhold consent to the processing in case of changes to the information given to you regarding the processing of your information. In connection thereto, the Company shall adequately explain to you the extent of the withdrawal requested including consequences thereof, which may include disclosure whether or not the Personal Data will be subject to further processing.",
      "Right to erasure or blocking.\\xa0You have the right to suspend, withdraw or order the blocking, removal or destruction of your Personal Data. Right to damages.\\xa0You may claim compensation if you suffered damages due to inaccurate, incomplete, outdated, false, unlawfully obtained or unauthorized use of Personal Data. Right to file a complaint.\\xa0You may file a complaint if you are the subject of a privacy violation or personal data breach, or if you are personally affected by a violation of the Privacy Laws.",
      "Right to rectification.\\xa0You have the right to dispute any inaccuracy or error in your personal data and request to correct it, unless such request is unreasonable. Right to data portability.\\xa0This means that you have a right to obtain a copy of your Personal Data either in an electronic or structured format to give you more control and manage your Personal Data."
    ]
  },
  {
    "heading": "Requests, Access, Recourse And Questions Regarding This Privacy Statement",
    "paragraphs": [
      "You are entitled to request that we: Provide you with a copy of your Personal Data and inform you of: (a) the source of your Personal Data; (b) the purposes and methods of processing; (c) the data controller’s identity; and (d) the entities or categories of entity with whom your Personal Data may be shared; Cease processing your Personal Data, in whole or in part, as may be personally requested, save to the extent it is lawful to do so without consent under the Privacy Laws;",
      "Refrain from transferring your Personal Data to third parties for the purposes of direct marketing or any other purposes not allowed; and Correct any errors in your Personal Data; and Update your Personal Data as required. If you have questions, concerns, complaints, or suggestions regarding our compliance with the Privacy Laws or if you wish to exercise your rights to access, rectification, object, portability, or deletion in instances allowed under the law, you may contact us through our Data Protection Officer as follows: Address:\\u2028NAC Tower 32nd St., Fort Bonifacio, BGC, Taguig City, 4th District, NCR, 1630, Philippines.",
      "Email :\\xa0hello@solvivaenenergy.com Please use the following subject format:\\u2028Inquiry on Data Privacy We will make every reasonable effort to correct, update, and respond to your request promptly, unless we require further information from you in order to fulfill your request, and in each case, subject to legal and other permissible considerations. We will also investigate and endeavor to resolve complaints and disputes regarding use and disclosure of Personal Data in accordance with the Privacy Laws and other data privacy and protection policies we have put in place.",
      "You have the option of referring to the NPC any complaint that cannot be resolved with us directly.\" 1"
    ]
  }
];
